### ISSUE TITLE
[rust] dependency to deleted branch

### ISSUE THREAD

**Issue by rdettai** [ballista-compute/ballista#100]
The `cargo.toml` is pointing to `rev = 0b678164ffe04debc5244beebdfc259b75c50bd7` which seems to have been deleted. I've tried a few other revisions but none seem to work (in the latest revisions the Arrow Flight proto changed, but I also have issues compiling older revisions)

Also is there a reason to point to the [andygrove](https://github.com/andygrove/arrow) fork intead of the [arrow](https://github.com/apache/arrow) repo ?

**Comment by andygrove** [comment]
Fixed
