### ISSUE TITLE
Non-kube clusters

### ISSUE THREAD

**Issue by LucioFranco** [ballista-compute/ballista#12]
Hi andy! This project looks awesome, I was curious if you had any ideas about supporting other clustering techniques that are not based around kube?

**Comment by andygrove** [comment]
I'm pretty attached to building this as a Kubernetes-native solution at this point, but once the project is a little farther along it would be good to review this and see if it is feasible to build in an abstraction layer to support other orchestration frameworks in the future.

**Comment by andygrove** [comment]
Closing this for now. I'm still open to supporting other clustering techniques in the future but we need to get something working on k8s first, IMO.
