### ISSUE TITLE
Error: "Failed to locate format/Flight.proto in any parent directory" in Rust build

### ISSUE THREAD

**Issue by mparaz** [ballista-compute/ballista#127]
Hi! I found this in both local and Docker builds. 
commit `9f362a017424f7814b1c980bb28faec36c851781`

```
$ cd rust
$ ./build-docker-image.sh
...
   Compiling arrow-flight v0.17.0
error: failed to run custom build command for `arrow-flight v0.17.0`

Caused by:
  process didn't exit successfully: `/opt/ballista/target/release/build/arrow-flight-095bc3c9594c8f7f/build-script-build` (exit code: 1)
--- stderr
Error: "Failed to locate format/Flight.proto in any parent directory"
```
I see that in your Arrow ticket: https://issues.apache.org/jira/browse/ARROW-8536
that this `format` directory is the workaround. Is there something else I need to do to build?

Thanks.

**Comment by andygrove** [comment]
Hi @mparaz I've been busy fixing packaging issues and writing documentation. Could you try again with latest from master using this documentation as a guide and let me know if this resolves it?

https://ballistacompute.org/docs/release-process.html

**Comment by mparaz** [comment]
Hi @andygrove ! I pulled again from `master` - now on `73080babe1b489febc6211347940a53d74f272f4` - and updated rust.

I still get the same error when running `./dev/build-rust.sh`'.

I can try fixing it, any suggestions on how to proceed?

**Comment by mparaz** [comment]
I was able to build by cloning Arrow and pointing `Cargo.toml` to it:

```
arrow = { path = "/path/to/arrow/rust/arrow" }
arrow-flight = { path = "/path/to/arrow/rust/arrow-flight" }
datafusion = { path = "/path/to/arrow/rust/datafusion" }
```
