### ISSUE TITLE
[Rust] Cannot add filter to TPCH query 1

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#251]
If I add the filter to the query, I get this error:

```
DataFusionError(ExecutionError(\\\"Columns need to be resolved before column indexes resolution rule can run\\\"))
```

**Comment by andygrove** [comment]
Root cause is https://issues.apache.org/jira/browse/ARROW-9542

**Comment by jorgecarleitao** [comment]
Should we fix that stuff on datafusion for a merge ASAP, or did we already miss the release window for the 1?

**Comment by andygrove** [comment]
Too late for DataFusion 1.0.0 .. RC2 vote is going well, so the release is likely imminent.

I just started working on a workaround here though and will have a PR up in an hour or so.
