### ISSUE TITLE
Add SQL support to scheduler

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#262]
As a user, I would like to run SQL against a cluster, rather than having to use the DataFrame API.

The rough steps involved are:

- Add new SQL action to the Action protobuf message
- Add new `sql(sql: &str)` method to the client context, which constructs the protobuf action and sends it to the scheduler/executor
- Add code to the executor to handle the sql action .. it will need to invoke methods on a DataFusion context to translate sql to logical plan. The executor already has code to execute the logical plan.

The only tricky part here is managing state for `CREATE TABLE` statements. These tables will be referenced in subsequent `SELECT` statements. We really need to manage this state client-side and send a list of registered tables (with their schemas) when executing a SQL statement. However, we don't want to have to parse SQL in clients in all languages either, so there is probably some hybrid approach here where the client sends the `CREATE TABLE` to the scheduler and gets protobuf back with the table registration and it can simply send that with subsequent SQL statements in the same session.

**Comment by houqp** [comment]
Do we expect client to use different scheduler for subsequent queries after `CREATE TABLE` statement? If not, would it make sense to keep the state in the scheduler instead?

**Comment by andygrove** [comment]
That's a good question. Perhaps that makes sense but it depends if we want session affinity / stateful connections between client and scheduler. I will think about this some more.

**Comment by houqp** [comment]
If the size of state is small, then I think keeping the state in client is a more scalable and robust design.

**Comment by andygrove** [comment]
Yes, the state is small. It is basically a mapping from table name to list of filenames + schema.
