### ISSUE TITLE
[Rust] Get 0.4 branch compiling against Arrow 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#264]
I created a `branch-0.4` with the intention that we can build against latest Arrow snapshots as we continue development. The code won't compile without changes though due to recent PRs that were merged into Arrow.

**Comment by andygrove** [comment]
@jorgecarleitao Maybe you want to take this one?

**Comment by jorgecarleitao** [comment]
I can take it.

**Comment by jorgecarleitao** [comment]
fyi the code on the hash aggregate will benefit from https://github.com/apache/arrow/pull/7687
