### ISSUE TITLE
[Marketing] Consider Updating Important External Links to New Project URL

### ISSUE THREAD

**Issue by mkvalor** [ballista-compute/ballista#276]
One of the top search results for "rust" within this broad problem domain is the HN story[1] about Andy Grove's blog article[2] introducing Ballista.  Unfortunately, link available in that blog post is for the old, deleted project under Andy's personal account, rather than this project under the ballista-compute org.  A person in a hurry might view the blog post, click the link, get the 404 (as I did), and assume the project had closed down for some reason.

I suggest it's worth the effort to edit the original blog post so that readers are directed to this project. If Andy or other top contributors here have other popular blogs/articles/resources with the old link, please consider updating those as well.

[1] https://news.ycombinator.com/item?id=20456273
[2] https://andygrove.io/2019/07/announcing-ballista/

**Comment by andygrove** [comment]
Thanks @mkvalor for filing this. Great point. I have just updated all the github urls in my blog.
