### ISSUE TITLE
Improve development documentation for rust

### ISSUE THREAD

**Issue by jorgecarleitao** [ballista-compute/ballista#277]
Currently, we have the following docs:

```
README.md
docs/development-environment.md
docs/integration-testing.md
CONTRIBUTING.md
kubernetes/README.md
the user guide
```

From `README.md` to `docs/development-environment.md`, a dev needs to:

1. scroll to bottom
2. click `CONTRIBUTING.md`, 
3. scroll to bottom
4. click `developer docs`, 
5. press `development-environment.md`

`kubernetes/README.md` is not reachable from README, and development-environment.md does not really address how to bootstrap this thing.

IMO we can improve discoverability.

I propose that the refactor this and instead of working with concepts, we work in user-stories. Specifically: as a developer that changed some code in rust, I want to

1. be able to run unit tests (trivial with cargo)
2. be able to run the integration tests with my changes
    2.1. be able to build the rust docker image so that I can test it in integration
    2.1. run the docker-compose with the tests
3. be able to run my image in mini-kube
4. be able to run my image a k8 cluster

and we have one `.md` document that goes through all these steps, section by section.

**Comment by andygrove** [comment]
This sounds great. We will need to do the same for the JVM project eventually. I did push a refactor on the docs last night so plese make sure you have the latest before starting to make these changes.

**Comment by andygrove** [comment]
We also need to bear in mind that some docs are not specific to Rust, such as how to find or generate benchmark data for NYC Taxi and TPC-H.

**Comment by andygrove** [comment]
I will work on this over the coming weekend
