### ISSUE TITLE
Kubernetes URL should be configurable

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#28]
Currently, the Kubernetes URL is hard-coded and it needs to be configurable. 

We need to think about how we want configuration to work in general. I am a fan of twelve factors [0] in general, and would encourage anyone working on this issue to read the configuration section there at least.

[0] https://12factor.net/

**Comment by sd2k** [comment]
Many other clients that talk directly to Kubernetes (e.g. [helm](https://github.com/helm/helm) and [stern](https://github.com/wercker/stern)) take `--kubeconfig`, `--context` and `--namespace` arguments in their CLIs and use the standard Kubernetes config file to figure out connection details. Perhaps that model would make sense here, too?

**Comment by andygrove** [comment]
Closing this as no longer relevant, since deployment now is just a yaml file so users have full control.
