### ISSUE TITLE
[Rust] Separate scheduler and executor into two different processes

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#293]
The scheduler and executor need splitting into two processes. It should be possible to use the Rust scheduler with Java executors, for example. Also, we want to scale schedulers and executors separately. Schedulers are light-weight processes and don't need much resource.

**Comment by phungleson** [comment]
Hi @andygrove I like the idea ballista/arrow and would like to help.

This issue in particular, does it mean that we will create a new file i.e. `scheduler.rs` and split the scheduler code to that new file?  `BallistaFlightService` seems to use both scheduler and executor though?

https://github.com/ballista-compute/ballista/blob/main/rust/ballista/src/bin/executor.rs#L81-L82

It would be great if you give me some direction so I can get things up and running quickly. Thanks in advance, Son.

**Comment by andygrove** [comment]
The scheduler and executor should be independent. It should be possible to use the same scheduler both with a Rust executor and a Java executor, for example.

It should be possible to scale the scheduler(s) and executor(s) separately, so this is a bit of an architectural change since the schedulers will need to know how to discover the executors and clients will now need to know how to discover the schedulers, so this isn't a trivial change unfortunately.

I've going to be spending some time working on this project again next week since I have some time off work for the holidays and the most pressing task currently is upgrading the project to use Arrow/DataFusion 2.0.0. Once that is done, I plan on spending time on the scheduler part and that might be a better time to contribute to that part.

It would be great to get some help with the project. Perhaps we can chat more in gitter or discord.

**Comment by phungleson** [comment]
Thanks Andy, that's great news, yeah I got the idea, it sounds like an important part (perhaps of any distributed system) and great way to explore ballista. I am open to look into both rust and jvm or any vertical, let me know if you happen to think of any subtasks and yeah let's discuss further in discord, thanks again

**Comment by andygrove** [comment]
This has now been done
