### ISSUE TITLE
Add helm chart to the project

### ISSUE THREAD

**Issue by jorgecarleitao** [ballista-compute/ballista#311]
Currently we have 4 kubernetes configurations, each with small variations of each other. I think that it would be beneficial to provide an helm chart that templates those configurations thus allowing users to configure the cluster and manage releases.

IMO this will also allow us to more easily benchmark with a variable number of executors and spark vs rust.

**Comment by andygrove** [comment]
Sounds good. I have a fair bit of experience with Helm too. We could even add helm tests to verify deployments and integrate that with CI if someone provides funding for some infrastructure (like an always-on k8s cluster).

**Comment by joshthoward** [comment]
@andygrove I built out a Helm chart for Ballista [here](https://github.com/joshthoward/charts). It will need to go in its own repo to list on ArtifactHub. Happy to transfer ownership to ballista-compute.

**Comment by andygrove** [comment]
Thanks Josh! I will try and find time tomorrow to take a look.

**Comment by andygrove** [comment]
I didn't get a chance to test deploying it, but this looks great. Could you initiate a transfer to the ballista-compute org?

**Comment by joshthoward** [comment]
@andygrove I'm getting an error "You don’t have the permission to create public repositories on ballista-compute". If you don't see the request, could you fork and I will then delete? There are no current forks so yours would become the parent ideally.

**Comment by andygrove** [comment]
@joshthoward ok, done

**Comment by joshthoward** [comment]
@andygrove Okay. I've deleted mine. The ballista-compute/charts repo is now the primary. 

From the charts repo you can use the following command to deploy Ballista in it's own namespace:
```
helm install --create-namespace ballista . -f values.yaml
```

I'll add the repo to Artifact Hub, but we should be good to close this issue.
