### ISSUE TITLE
[Spark] Spark executor should support TPC-H query 1

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#315]
I would like to be able to execute TPC-H query 1 against the Spark executor, for benchmarking against the Rust executor.

This will involve implementing the new protobuf methods for the Spark executor and ensuring that the query plan can be fully translated to a Spark plan.

**Comment by kyprifog** [comment]
I'm guessing from the way this is phrased you mean for this benchmark to be built using the rust bindings for spark and not just side by side comparison with vanilla spark?
