### ISSUE TITLE
[Rust] Implement Wasm code-generation for query execution

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#317]
Ballista currently implements an interpreted Volcano model and this is inefficient compared to a code generation approach (as used by Spark).

We should explore generating Wasm on a per-query basis, with the generated code relying on Ballista libraries.

**Comment by josephjacks** [comment]
I really love this idea. + my friend @syrusakbary who I think would love to help/learn about this use case in the data integration world.
