### ISSUE TITLE
Where should data go for queries? 

### ISSUE THREAD

**Issue by joshthoward** [ballista-compute/ballista#334]
The title sums up the issue, but here is where I am at...

A couple of days ago, I created this [issue](https://github.com/ballista-compute/ballista/issues/332) for a build issue I was seeing. After getting the build right, I'm seeing other runtime issues:  

```
$ cargo run yellow_tripdata_2019-12.csv --host localhost --port 50051
   Compiling distributed-query v0.4.0-SNAPSHOT (~/Workspace/ballista/rust/examples/distributed-query)
    Finished dev [unoptimized + debuginfo] target(s) in 9.73s
     Running `~/Workspace/ballista/rust/target/debug/distributed-query yellow_tripdata_2019-12.csv --host localhost --port 50051`
Ballista v0.4.0-SNAPSHOT Distributed Query Example
Path: yellow_tripdata_2019-12.csv
Host: localhost:50051
Creating expensive one-off flight connection to execute an action
Error: General("Status { code: Internal, message: \"DataFusionError(IoError(Os { code: 2, kind: NotFound, message: \\\"No such file or directory\\\" }))\" }")
```

The `yellow_tripdata_2019-12.csv` is in my local directory. From the "Creating expensive one-off flight connection to execute an action" message, it sounds like the data is being sent to the pods, but the data cannot be found in the pod. I've also tried to reference the data that I've placed in the remote mounted persistent volume. This also fails. 

Where should data go for queries? Do I need the same folder structure on my local machines as the pods?

**Comment by joshthoward** [comment]
BTW... The port-forward in another shell is registering the connection to localhost...

**Comment by andygrove** [comment]
Sorry for the delay in responding. This error message is improved in DataFusion 3.0.0 (about to be released) so that it shows the path that it cannot find.

You may need to add some printlns to see what path it is looking for.

**Comment by andygrove** [comment]
@joshthoward Error messages are now improved so this problem should be resolved now
