### ISSUE TITLE
Finish implementing new serde module

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#341]
There is a partially implemented [serde module](https://github.com/ballista-compute/ballista/tree/main/rust/ballista/src/serde) for serializing and deserializing logical and physical plans. I could use some help in completing this implementation.

We could break the work down into multiple issues if multiple people are interested in collaborating on this.

**Comment by seanpianka** [comment]
I'm willing to help if you can break down the work into separate issues and clearly identify the desired outcome from the de/serializer implementations.

**Comment by jorgecarleitao** [comment]
Me too!

**Comment by andygrove** [comment]
Next up is implementing the rest of the logical expressions!

https://github.com/ballista-compute/ballista/issues/368
https://github.com/ballista-compute/ballista/issues/369
https://github.com/ballista-compute/ballista/issues/370
https://github.com/ballista-compute/ballista/issues/371
https://github.com/ballista-compute/ballista/issues/372

**Comment by bjcohen** [comment]
Filed https://github.com/ballista-compute/ballista/issues/388 for Negative, InList, Wildcard

**Comment by andygrove** [comment]
This is mostly done, and new issues were filed for the remaining items:
