### ISSUE TITLE
Implement serde code for logical expressions "Not, IsNull, IsNotNull"

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#368]
The module at  `rust/src/serde/logical_plan` provides serde code to convert DataFusion logical plans to/from protobuf format.

It does not currently implement serde for the expression(s) mentioned in the title  of this issue. The goal for this issue is to implement the serde code  (both to and from protobuf) for these expressions, and ensure that there is a unit test demonstrating round-trip serde for a logical plan using these expressions.

It is possible that there is existing code in `rust/ballista-old/src/serde` that can be ported over. If not, it is usually possible to figure out  an approach by looking at the serde code for the expressions that are  implemented.

It may be necessary to add new expressions to the .proto file as well.

**Comment by edrevo** [comment]
dibs on this one!
