### ISSUE TITLE
Update serde code to support null literal values

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#373]
The serde code for literal values currently contains calls to `unwrap` and assumes that literal values always have a value, meaning that we currently do not support null literal values.

**Comment by edrevo** [comment]
One question @andygrove: does Datafusion use "typed nulls"? I see in https://github.com/apache/arrow/blob/4b7cdcb9220b6d94b251aef32c21ef9b4097ecfa/rust/datafusion/src/scalar.rs#L45-L81 that each type has an optional value. Not sure if that means that `null: String` has a different representation from `null: i8` or maybe I'm reading it wrong.

**Comment by andygrove** [comment]
@edrevo Yes, that is correct. DataFusion does support typed nulls.

**Comment by edrevo** [comment]
dibs on this one!
