### ISSUE TITLE
Docker github action frequently failing

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#376]
The Docker build part of github actions often fails with:

```
 4762552ad7d8: Layer already exists
674db2e99f30: Pushed
a7e00d82e596: Pushed
blob upload unknown
Error: Process completed with exit code 1.
```

My theory is that because this runs twice (push + pull_request) when we push to a PR branch, they are conflicting when trying to push to the same location at the same time.

**Comment by jorgecarleitao** [comment]
We could deactivate build on PR for this repo, thereby only triggering the PR build. Alternatively, we could not push the image on every push / PR.

I can take a look at this today.
