### ISSUE TITLE
Add Rust integration test client to github actions

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#396]
We need to build `integration-tests/rust` in the github actions to prevent regressions.

**Comment by jameswinegar** [comment]
I'll take this over the weekend. Should be simple since docker-compose is supported by actions.

**Comment by andygrove** [comment]
We should now use the TPC-H benchmarks for integration testing.

https://github.com/ballista-compute/ballista/tree/main/benchmarks/tpch

**Comment by andygrove** [comment]
There is now an [integration testing script] in the repo and we should get it running from github actions. I have been looking into using buildkite to run this but it might take me some time to set up.
