### ISSUE TITLE
[Design] How to support UDF/UDAFs in multiple languages

### ISSUE THREAD

**Issue by edrevo** [ballista-compute/ballista#431]
One of the reasons the ballista project currently has differently flavoured executors (Rust, JVM) is to support code extensibility in different programming languages. However, I think Apache Arrow provides an oportunity to take a different direction: since a UDF/UDAF is just a data-in, data-out function you really just need a calling convention to invoke them.

Custom UDFs could be implemented as a gRPC server (any well defined interface works, not just gRPC) that takes either an address in a shared memory page or a file path for a memory mapped file as its input, and a placeholder shared-memory/mmap file for the output. That would allow the custom UDF to read the input with no copy overhead and would allow the executor to read the result with no copy overhead too.

The custom UDFs could run as a sidecar pod in k8s or just as a local process in the executor machines in non-k8s deployments. This would allow writing JVM-based UDFs without the need of maintaining a JVM executor in Ballista.

For languages that compile to WASM, instead of a gRPC server + mmap file, the calling interface could be executing the WASM and providing an input and output [Memory object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory). That would make deployment for WASM UDFs easier, since they would get executed directly in the same process as the executor.

In order to provide nice ergonomics to users, I think the Ballista project should provide an SDK for the most popular languages (JVM, JS, Python, Rust, Go...).

**Comment by andygrove** [comment]
I like this idea a lot. It doesn't make sense to try and replicate a full executor in JVM. I have been thinking about moving the JVM query engine out to a separate repo for some time now and maintain it for the readers of How Query Engines Work since this implementation was used to provide examples for that book.

I filed a specific issue for adding Java UDF support: https://github.com/ballista-compute/ballista/issues/434

**Comment by houqp** [comment]
+1 for sharing input and output through shared memory. I think it would be best to go with the local process route even in k8s deployment though. It will help reduce overhead and make the implementation/behavior more consistent.
