### ISSUE TITLE
[Design] create simple json/toml format for representing tasks/apps to abstract away scheduler

### ISSUE THREAD

**Issue by richardanaya** [ballista-compute/ballista#44]
Rather than using straight up format used by a machine scheduler, we allow apps/executors descriptors to be defined in a simpler json/toml that gets turned into a specific scheduler format.

**Comment by andygrove** [comment]
@richardanaya  Sorry for the nearly 2 year delay in responding but Ballista is finally real and I am catching up on the backlog. We currently use protobuf to define query plans (logical and physical) as well as certain scheduler concepts (stages, tasks). Protobuf supports JSON encoding. Does that meet this requirement or are you thinking of something higher level?

**Comment by richardanaya** [comment]
@andygrove thanks for the reply! this idea may be outdated =) i'm sure you all have a better vision these days, closing this!
