### ISSUE TITLE
[Design] Streaming support

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#444]
This issue is to track discussions and feature requests around streaming. If you would like to see Ballista support streaming, please add comments on this issue to help us understand what you are looking for.

**Comment by j4ckcyw** [comment]
Scenario: doing interactive ad-hoc query.
Example: top 100 of employee salary (sort + limit) and top 100 of employee salary by department (agg + sort + limit).

Expected: able to see top 100 before entire query finishes. It is OK to poll the root executor for current result, knowing that the top 100 might change as more files are processed. I would also like to be able to cancel the query, if I'm already satisfied with the results.
