### ISSUE TITLE
Implement physical plan serde for these expressions

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#448]
See `ballista/src/serde/physical_plan/to_proto.rs`

```rust
        } else if let Some(_expr) = expr.downcast_ref::<Literal>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<CaseExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<CastExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<NotExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<IsNullExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<IsNotNullExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<InListExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<InListExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<NegativeExpr>() {
            unimplemented!()
        } else if let Some(_expr) = expr.downcast_ref::<ScalarFunctionExpr>() {
            unimplemented!()
```

**Comment by boaz-codota** [comment]
I'd love to contribute this issue, but I need further guidance. Like basically how can I generate the protobuf's rust representation.

**Comment by boaz-codota** [comment]
I've got stuck on `ScalarFunctionExpr` & `Literal` (I have no idea what to do).

And I thought I know what to do with `CastExpr` but got some weird compilation errors (will submit a PR for help once the last PR gets merged)

**Comment by andygrove** [comment]
@boaz-codota I will put up a PR for `ScalarFunctionExpr` shortly

**Comment by j4ckcyw** [comment]
@boaz-codota  @andygrove  Let me take a stab at `Literal`. ;)

**Comment by j4ckcyw** [comment]
Looks like Literal is already done. Doesn't hurt to add a test case for this ;)

**Comment by j4ckcyw** [comment]
Actually, looks like `Literal` is already done. 

https://github.com/ballista-compute/ballista/blob/df787c9e1ecc0e5236d6e5e416e0310b6bdceff7/rust/ballista/src/serde/logical_plan/from_proto.rs#L789
https://github.com/ballista-compute/ballista/blob/df787c9e1ecc0e5236d6e5e416e0310b6bdceff7/rust/ballista/src/serde/logical_plan/to_proto.rs#L960

test case with `Literal`
https://github.com/ballista-compute/ballista/blob/df787c9e1ecc0e5236d6e5e416e0310b6bdceff7/rust/ballista/src/serde/logical_plan/mod.rs#L785-L791

**Comment by boazberman** [comment]
@j4ckcyw the code you attached is for `logical plan`, but this issue is for `physical plan`. The code can be used as a reference but it is not the same.

**Comment by andygrove** [comment]
I think these are mostly done now
