### ISSUE TITLE
Example in README not creating K8s resources

### ISSUE THREAD

**Issue by thundergolfer** [ballista-compute/ballista#45]
### Description 

I've run into this issue when trying to run the repo example. I'm still investigating what could be going wrong, but thought it worth the time to throw up some info while I investigate. 

I'm running this: 

```
cargo run --bin ballista -- create-cluster --name nyctaxi --num-executors 12 --template examples/nyctaxi/templates/executor.yaml
```

Output from the program is: 

`Executed subcommand create-cluster in 1.566 seconds`

### Expected Output

A number of `ballista-nyctaxi-*` K8s resources when you run `kubectl get pods`

### Actual Output

`No resources found.`

### Further Information

**`minikube version` output:** `minikube version: v1.2.0`
**`minikube status` output:** 

```
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.101
```
**`kubectl cluster-info` output:** 

```
Kubernetes master is running at https://192.168.99.101:8443
KubeDNS is running at https://192.168.99.101:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**`kubectl version` output:** `Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by thundergolfer** [comment]
Looked at the source and saw it was just shelling out to `kubectl`. Ran the equivalent command locally, which is `kubectl apply -f temp.yaml`, and got: 

```
error: SchemaError(io.k8s.api.core.v1.SecretKeySelector): invalid object doesn't have additional properties
```

Googling around this turned out to be because my `kubectl` version was out-of-date for this project. Upgrading solved the issue ✅

----

It's weird that this Schema invalidation problem didn't create an error in the code that blew up at `expect(..)`, as the failing `apply` _did_ return a non-zero code when run in the console. 

I see there's an issue about using the Kube API directly instead of `kubectl`, but perhaps it's worth specifying the minimum kubectl version in the `README` or checking it in the CLI project at runtime.

**Comment by andygrove** [comment]
Closing as no longer relevent since deployment is now manual via kubectl and yaml
