### ISSUE TITLE
BallistaContext should get file metadata from scheduler

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#473]
Currently the BallistaContext simply wraps the DataFusion context, and any reference to Parquet/CSV files results in looking on the local file system for those files:

```rust
/// Create a DataFrame representing a Parquet table scan
    pub fn read_parquet(&self, path: &str) -> Result<BallistaDataFrame> {
        // convert to absolute path because the executor likely has a different working directory
        let path = PathBuf::from(path);
        let path = fs::canonicalize(&path)?;

        // use local DataFusion context for now but later this might call the scheduler
        let mut ctx = ExecutionContext::new();
        let df = ctx.read_parquet(path.to_str().unwrap())?;
        Ok(BallistaDataFrame::from(self.state.clone(), df))
    }
```

We should instead have the context send a gRPC request to the scheduler for the file metadata. This would allow a Ballista client to run against a remote cluster e.g. in the cloud and would be a step towards eventually supporting S3 and similar object stores.

**Comment by hmakait** [comment]
Interested in tackling this one! :)

**Comment by hmakait** [comment]
It looks like this issue should be based on #491 to avoid duplicating the integration of the context with the scheduler. Is it safe to proceed based on the existing branch, or should I wait? @andygrove

**Comment by edrevo** [comment]
@hmakait, the branch has been merged, so feel free to code away!
