### ISSUE TITLE
Implement web UI for scheduler

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#475]
We should implement a web UI in the scheduler that can be used to monitor the state of the cluster and view information on queries that are pending/running/completed/failed.

This issue is for creating the basic mechanism and then we can file additional issues for functionality, such as:

- view list of executors
- view query plan
- view query metrics
- cancel query

**Comment by msathis** [comment]
I can take this up 👍

**Comment by msathis** [comment]
@andygrove I did a quick wireframe https://miro.com/app/board/o9J_lSJQsYk=/

Attaching the image of the wireframe also so people can take a quick look. Please let me know how it looks & what's missing, so we can discuss the next steps. 👍 

<img width="766" alt="Screenshot 2021-02-26 at 12 55 44 PM" src="https://user-images.githubusercontent.com/2977899/109269430-7c0f2f80-7832-11eb-8396-3ca5374b9a40.png">

**Comment by andygrove** [comment]
Thanks @msathis this is exciting :smiley: 

I would say that the priorities, in order would be:

1. List of executors, showing UUID, host, port - this will really help in debugging cluster setup
2. List of queries
3. Click on query to go to query detail page showing list of query stages with status

For cpu/memory metrics my assumption has been that each process (scheduler + executor) would expose these to Prometheus so that people can use Grafana to view and alert on those, rather than us building those kinds of things into the Ballista UI.

**Comment by msathis** [comment]
Thanks for the review @andygrove 🎉 

I wanted some eye candy on the home page so added those cpu/memory stats. 😄 

I revised the design as per your comments. Please have another look. I'm finding it difficult to visualize the query detail page. Can you please share some more details on that? 

<img width="775" alt="Screenshot 2021-02-26 at 9 31 48 PM" src="https://user-images.githubusercontent.com/2977899/109324687-024f6400-787b-11eb-955b-eeff9ce2fcd5.png">

**Comment by andygrove** [comment]
Very nice. This will be a great start and I can write up a story for the query detail page

**Comment by djKooks** [comment]
@msathis seems great~
How are you planning to get information from ballista cluster?

**Comment by msathis** [comment]
@djKooks Hi, I don't have much information on that yet. I thought of getting the UI to a shape & then figure out that. Can you please give me some pointers? I would like to write rust code also if required :)

**Comment by djKooks** [comment]
@msathis oh, not a big thing.
Just wonder how to get the status information of cluster...

@andygrove is all data for UI is stored in etcd, or should we need to make several API to get information from cluster?

**Comment by edrevo** [comment]
@msathis , I think the query page should have details on which stages and partitions exist for the query and which of those partitions are pending/running/finished. For those that are running, a link to the specific executor that is running it would be nice. For those that are completed, the start and end timestamps. For those that are failed, the error message.

Most of this info will be accessible through the Scheduler State struct once https://github.com/ballista-compute/ballista/pull/574 is merged

**Comment by msathis** [comment]
Thanks @djKooks & @edrevo for the great insights. I will wait for your PR to get merged then! 👍

**Comment by msathis** [comment]
Small sneak peek into the UI to get early feedback @andygrove @djKooks @edrevo 

Between i made a naive logo just for time being. We can replace it with actual logo once it's ready.

<img width="1362" alt="Screenshot 2021-02-28 at 5 41 22 PM" src="https://user-images.githubusercontent.com/2977899/109418089-84ab6580-79ec-11eb-9387-cdbba2a99cf3.png">

**Comment by boazberman** [comment]
As a reference to this, I'd truly enjoyed using Trino (formerly Prestosql)'s web ui. It shows basically what @andygrove referred to, plus making it similar will make it easier for potential users to adopt ballista. 
![image](https://user-images.githubusercontent.com/14139261/109433734-a3c0ec00-7a1a-11eb-95b6-00e8acc48557.png)

Ref: https://trino.io/docs/current/admin/web-interface.html

**Comment by msathis** [comment]
Thanks @boazberman ! That seems like a pretty nice tool. We can take this as an inspiration to develop our own UI. I would prefer to not modify Trino UI for our use because

1.  We'll be limited to the functionality they offer. 
2. Innovating on our own will not be possible.
3. The UI isn't hard. And we can easily build a modern UI in quick time.

But at the same time we can take inspiration from Trino UI & incorporate similar features here. My two cents.

**Comment by msathis** [comment]
I've created a basic scheduler UI in [Draft PR 626](https://github.com/ballista-compute/ballista/pull/626). 

@edrevo @andygrove I would like your input in figuring out the next steps. The question which is lingering in my mind now is

How do we expose the schedular state to the UI? REST api or GraphQL? 

And where should the API server should live? As part of scheduler or as another component?
