### ISSUE TITLE
Implement ability to load configuration properties from file

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#477]
When launching the scheduler and executor processes, we need the ability to specify a configuration file containing configuration options.  For example, `cargo run --bin executor --conf-file myconf.properties`.

The configuration file will consist of name-value pairs. For example:

```
ballista.default_batch_size=32768
ballista.feature.distributed.enabled=true
```

**Comment by Shamazo** [comment]
I could take a look at this tomorrow

**Comment by andygrove** [comment]
Fixed in https://github.com/ballista-compute/ballista/issues/490
