### ISSUE TITLE
Implement from_proto for logical operator InListExpr & NotExpr

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#494]
https://github.com/ballista-compute/ballista/pull/488 implemented to_proto, now we need from_proto

**Comment by hmakait** [comment]
I'll take a look at this one.

**Comment by hmakait** [comment]
@andygrove: As a quick question for understanding, shouldn't `compile_expr` already take care of deserializing physical expressions? https://github.com/ballista-compute/ballista/blob/6308a98ec573e838b0dfde941aa37534c48b51c6/rust/ballista/src/serde/physical_plan/from_proto.rs#L215-L231

**Comment by j4ckcyw** [comment]
If I understand correctly, you need to implement a case in the match. E.g. for Empty expression: https://github.com/ballista-compute/ballista/blob/82543a0a5c78a05c4a436a24254a8e2529623ba1/rust/ballista/src/serde/physical_plan/from_proto.rs#L220 

You can write a test case to find out if it is already done. 
https://github.com/ballista-compute/ballista/blob/6308a98ec573e838b0dfde941aa37534c48b51c6/rust/ballista/src/serde/physical_plan/mod.rs#L67

**Comment by andygrove** [comment]
Thanks @hmakait for adding the test. For each operator we need to implement to/from proto for the logical expression and to_proto for the physical expression (which just converts it into a logical expression and calls the logical to_proto). comile_expr takes care of the from_proto part for physical expressions.
