### ISSUE TITLE
Produce optimized binaries for releases

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#549]
According to the benchmark documentation, adding these flags will improve performance.

```
RUSTFLAGS='-C target-cpu=native -C lto -C codegen-units=1 -C embed-bitcode'
```

We should consider having a version of the Docker image that is built with these flags and use that version when running benchmarks.

**Comment by Dandandan** [comment]
@andygrove for the docker image I think you don't want to compile with `target-cpu=native` as it makes the binary non-portable. It is more something to document for people wanting to build ballista/DataFusion from source.

Adding `SIMD` + `snmalloc` features (or mimalloc) and the lto stuff do improve performance though.

**Comment by Dandandan** [comment]
I might have some time for this tomorrow.
