### ISSUE TITLE
Scheduler gRPC should support receiving SQL strings (as well as logical plans)

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#567]
The scheduler gRPC method `ExecuteLogicalPlan` should be renamed to `ExecuteQuery` and the `ExecuteQueryParams` protobuf message should be updated to support receiving either a logical plan or a SQL string:

```protobuf
message ExecuteQueryParams {
  oneof query {
    LogicalPlanNode logical_plan = 1;
    string sql = 2;
  }
}
```

The implementation should be updated to support the SQL case and would simply create a logical plan from it and then delegate to the existing code for executing the logical plan. 

This is required by the JDBC driver and other clients that simply want to execute SQL against a cluster.

**Comment by fitzoh** [comment]
Taking a closer look, is this made redundant by #577?
