### ISSUE TITLE
ExecutePartition should accept multiple partitions

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#569]
Currently, the scheduler `ExecutePartition` request accepts a single partition. This means that we sometimes send multiple of these requests to the same executor - one per partition. Not only does that have serde and networking overhead, it also means we miss out on some optimizations in the excutor, such as https://github.com/ballista-compute/ballista/issues/568.

**Comment by j4ckcyw** [comment]
IIUC, below is what needs to be done. Quick question: create a new api? or just modify existing api?

This is where it execute partition one-by-one. To implement this issue, it need to batch partition_id by hosts (executors).
https://github.com/ballista-compute/ballista/blob/f2eb9e2051b9105030272535d5df7419c0d42428/rust/ballista/src/scheduler/planner.rs#L304-L315

server api
https://github.com/ballista-compute/ballista/blob/f2eb9e2051b9105030272535d5df7419c0d42428/rust/ballista/src/executor/flight_service.rs#L89

client calling api
https://github.com/ballista-compute/ballista/blob/f2eb9e2051b9105030272535d5df7419c0d42428/rust/ballista/src/client.rs#L65-L71

**Comment by andygrove** [comment]
@j4ckcyw Yes, exactly. ballista.proto will also need updating to make partition_id a repeating field

**Comment by andygrove** [comment]
I am taking a look at this now and will create a PR soon that at least gets some of the plumbing in place for this
