### ISSUE TITLE
Move ExecutePartition code from do_get to do_action in flight_service.rs

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#578]
We should move the `ExecutePartition` code from `do_get` to `do_action` in `flight_service.rs` for the following reasons:

1. This is a more accurate use of the Flight API - do_get is intended for retrieving streams of data
2. It would allow us to use protobuf to serialize the results (path + statistics) rather than constructing a RecordBatch for this metadata

**Comment by fitzoh** [comment]
Would this mean adding a new `ExecutePartitionResponse` protbuf that contains the path + stats?

**Comment by andygrove** [comment]
> Would this mean adding a new `ExecutePartitionResponse` protbuf that contains the path + stats?

Yes.

**Comment by edrevo** [comment]
@andygrove, just fyi, I'm following a different approach in https://github.com/ballista-compute/ballista/pull/574. In that PR I am moving towards the direction described in https://github.com/ballista-compute/ballista/issues/463 and I am starting to move the code that executes a partition away from the FlightProtocol and into the scheduler gRPC interface.

If you think that's not a good direction please do comment on that PR.
