### ISSUE TITLE
Executor needs to control how many concurrent tasks run

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#580]
The executor has a `concurrent_tasks` argument which is currently ignored. We need to control how many concurrent tasks can run per-executor in order to manage memory pressure.

**Comment by edrevo** [comment]
If anyone wants to take this, the starting point would be https://github.com/ballista-compute/ballista/blob/a0c609f3a43ed316df6c21c3e04ce7de726455d4/rust/ballista/src/bin/executor.rs#L111

**Comment by boaz-codota** [comment]
I'm tackling this issue.  I thought about changing the `running_tasks` to hold references to tasks that did not finish using `Vec<Weak>`, then before making a request for more work from the scheduler iterate over the vec and remove all cleaned references. This way I push a weak reference to the `running_tasks` list and does not need to maintain it afterwards (the weak reference will resolve to null in upgrade after the task is finished). This will save some locks as the tasks won't need to lock the list when they finish running (the weak reference will be cleaned away).
My only question is whether there was a reason as to why `task_status.push` was called in the cleanup phase (the thing that happens at the start of the loop) and not right after this resolves:
```rust
let r = executor_client
                        .execute_partition(
                            task_id.job_id.clone(),
                            task_id.stage_id as usize,
                            vec![task_id.partition_id as usize],
                            plan,
                        )
                        .await;
```

I'd love to hear opinions about the purposed implementation. Thanks!

**Comment by edrevo** [comment]
`task_status` is a variable that is scoped in the loop:

https://github.com/ballista-compute/ballista/blob/a0c609f3a43ed316df6c21c3e04ce7de726455d4/rust/ballista/src/bin/executor.rs#L69-L71

So pushing it after the call to execute_partition would mean losing that information, since the next loop iteration will start with an empty `task_status`.

Your plan of using weak references sounds good to me.

**Comment by boaz-codota** [comment]
I ended up using a mspc channel & AtomicUsize that fitted all of my needs. Let me know what you think on the PR.
