### ISSUE TITLE
[design] generic system testing infrastructure 

### ISSUE THREAD

**Issue by Shamazo** [ballista-compute/ballista#587]
Going forward I think Ballista will need some generic system testing infrastructure. I am proposing we write this in Python and make use of the PyUnit framework. While this library is intended for unit testing, I have found it works quite well for generic system testing. I think python is a good choice for this because it is system agnostic and will allow us to write system tests for all of the Ballista components in a single place.  

I have three high level goals:
- test correctness
- make debugging for developers easy
- portability, we don't want to tightly integrate testing infrastructure with CI system and tests should be able to run locally 

The core component is the Harness class which derives from [unittest.TestCase](https://wiki.python.org/moin/PyUnit). Harnesses for specific tests can derive from our base Harness class, e.g for testing python bindings, rust bindings and JDBC. This provides a nice testing life cycle. For example if we have a harness with testing methods `test_x()` and `test_y()` the life cycle looks like: 
 
- setUpClass() # Set up for the entire Harness - create resources on a kubernetes cluster. 
- setUp() # set up before each test - 
- test_x()
- tearDown() # tear down after each test
- setUp()
- test_y()
- tearDown()
- tearDownClass() # tear down after all tests are complete - remove created resources 

In `setUpClass()` we can spin up a local kubernetes cluster using minikube/microk8s. I plan to write a nice wrapper script for cluster utilities. (cluster.py in the diagram)

We need an entry point to run our tests (runner.py in the diagram). This script should be usable in CI and locally for debugging. I think we could use something like [xml runner](https://github.com/xmlrunner/unittest-xml-reporting) to get xml reports which can be consumed by a CI server. 

I am not sure how to integrate this with buildkite yet, but my goal is to write infrastructure that should work anywhere and not integrate too tightly with any one CI system. 

I am going to start with the `cluster.py` utility. 

![image](https://user-images.githubusercontent.com/5744542/108606405-e8e47e80-7387-11eb-93d3-bbae6efbc01d.png)

**Comment by jankatins** [comment]
Just fyi as a Python person: i think the most commen unit testing framework in python is pytest, used by most major python data packages (pandas, dask, marplotlib,...). It allows for ways to define tests in other ways than python, eg here is an example plugin to run sql code as tests: https://pypi.org/project/pytest-sql-bigquery/ In a company setting I once wrote something similar to collect test cases from sql files: comparing output from top vs bottom. Worked nicely and was like 100 lines of python code.

**Comment by Shamazo** [comment]
I'll look into how pytest could work. I was going to start with pyunit because I am familiar with it and have used a similar architecture before for system tests for distributed code.

**Comment by houqp** [comment]
I would recommend pytest as well since it's basically the default test framework to use for python projects nowadays.

**Comment by Shamazo** [comment]
@jankatins @houqp  do either of you have links to examples I could read through where PyTest is used to create a test suite with shared resources. e.g creating/modifying a Kubernetes cluster? I've used PyTest before for unit testing python projects, but not for system tests and I am trying to grok how that might work.

**Comment by andygrove** [comment]
I like the general approach here and I agree that Python makes sense. In my day job, we use PyTest so I would also like to use that if possible.

I've been doing a lot of benchmark automation work in Python lately and I intend to focus quite a bit of my time on doing something similar for Ballista so that I can run many benchmarks on the dedicated server that I have to try and catch performance regressions early.

**Comment by houqp** [comment]
@Shamazo, I recommend using https://docs.pytest.org/en/stable/fixture.html to manage shared resources. It's pretty flexible in the sense that you can create fixtures at different scopes based on the need of your tests.
