### ISSUE TITLE
Add support for ShuffleHashJoin

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#595]
We currently use a hash join which loads one side into memory and then streams the other side. This is not very scalable because for every probe-side partition, the entire build-side has to be loaded into memory.

`ShuffleHashJoin` works by repartitioning both inputs using hash partitioning of the join keys, with the same number of partitions on both sides of the join. This means that the resulting partitions can be joined in parallel and smaller amounts of data need to be loaded into memory.

For example, let's assume we have two inputs that are 8 GB each and 8 partitions each. Let's also assume we have 8 executors.

In the current implementation, this would result in each executor processing one partition of the probe-side (streaming) input. Each of these executors would need to load the entire build-side relation into memory. This means we have 64 GB (8 x 8GB) being loaded into memory.

With ShuffleHashJoin, each executor would only need to load 1 build-side partition into memory so now we are only loading 8GB data rather than 64GB of data, and the memory overhead can be reduced further by increasing the number of partitions and restricting the number of partitions that can be executed concurrently.

We will need to implement hash partitioning (either in Ballista or preferably in DataFusion) before we can implement this feature.

**Comment by Dandandan** [comment]
I hope to make some progress on this this week:
https://github.com/apache/arrow/pull/9548

Seems remaining part shouldn't be too hard
