### ISSUE TITLE
Consider using structopt to define the CLI

### ISSUE THREAD

**Issue by sd2k** [ballista-compute/ballista#60]
If other tools in this space are anything to go by, we'll end up with a lot of options in the CLI, so having arg parsing handled automatically would be great.

**Comment by rrichardson** [comment]
+1 for structopt.   My 2nd choice would be Docopt, which tends to encourage better online documentation. :)

**Comment by andygrove** [comment]
Sounds good to me

**Comment by andygrove** [comment]
I'm now using structopt. Thanks for the advice!
