### ISSUE TITLE
Implement minimal REST API in the scheduler

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#631]
We should start building a REST API in the scheduler using [rocket](https://crates.io/crates/rocket). The web UI can use this REST API and it would also allow users to use other tools (such as curl) to write scripts that get metadata from the scheduler.

For this issue, I would suggest just implementing one method to return a list of executors. We can then write up issues for additional functionality.

**Comment by boaz-codota** [comment]
I think I'll tackle this next week if no one does it by then

**Comment by msathis** [comment]
@andygrove Rocket needs nightly. Maybe we should go with https://github.com/seanmonstar/warp ?

**Comment by andygrove** [comment]
> @andygrove Rocket needs nightly. Maybe we should go with https://github.com/seanmonstar/warp?

I didn't realize that Rocket required nightly Rust. Warp looks good. It is based on hyper which we are already using for the gRPC servers.

**Comment by houqp** [comment]
I would recommend either warp or actix-web, rocket is also not being actively maintained at the moment. Warp would probably be the ideal framework for simplicity sake.

**Comment by edrevo** [comment]
+1 for warp

**Comment by djKooks** [comment]
Looks good~

**Comment by msathis** [comment]
It's time to ask for help. I'm fighting with borrow checker to fix lifetime issue for last couple of days. Since i'm new to rust, i am finding this hard. I've raised a draft PR with what i have so far. Please someone help me to get it compile. 🙏 

https://github.com/ballista-compute/ballista/pull/648
