### ISSUE TITLE
Ballista Distributed Compute has moved! Please bookmark and star the new repo!

### ISSUE THREAD

**Issue by andygrove** [ballista-compute/ballista#654]
Ballista has now been donated to Apache Arrow and has moved to a new repo!

Unfortunately, we lost more than 2200 GitHub stars in the process so it would be great if everyone could :star: the new repo and help keep the project momentum going :rocket: 

The new repo is at  https://github.com/apache/arrow-datafusion

Thanks for your support!

**Comment by andygrove** [comment]
@wolf4ood @timClicks @guywaldman @esneko @franchb @aheart @msmakhlouf @timothyklim @kujon @MerelyAPseudonym @dimlev @lipengsh @zoosky @Ktakuya332C @oblitum @andrewbanchich @redaready @kud1ing @jimmyrcom @jezell @james-andrewsmith @compasses @yenwel @wub @montanaflynn @tbutler78 @tuananh @daodao2007 @thundergolfer @eevmanu @vithalreddy @rsohlot @eenchev @woonhak @ygouzerh @DouglasOrr @atombender @tomhoule @jinyangustc @johndagostino @gernest @Kabie @dlom @mbrobbel @Neuw84 @fernandoracca @orhuncirakli @ahmgeek @tobgu @royge @nmrshll @plokhotnyuk @joostshao @mytrile @JohnClema @tangwz @T-Jedsada @tnpxu @myhau @viktorku @chansuke @giannissc @vamsiautomatad @w1kke @seruman @Chaz6 @PaoloCifariello @sd2k @mbana @exgens @aleksandersumowski @cbonitz @RMKD @ocramz @BrunoScheufler @igponce @ZhangHanDong @sergey-melnychuk @nottxy @Ruslanmsv @grovesNL @gklein @seeekr @lifa123 @ratamovic @andriisoldatenko @placrosse @sjaek @rjammala @serega @dgolhiardi @rogersmarin @damianmoore @dojiong @haraball @simple555a @piggybox @alexsward @mxuribe @syegulalp 

:point_up: Ballista has moved to https://github.com/apache/arrow-datafusion .. could you do me a favor and star the new repo?

**Comment by andygrove** [comment]
@nmrshll @plokhotnyuk @joostshao @mytrile @JohnClema @tangwz @T-Jedsada @tnpxu @myhau @viktorku @chansuke @giannissc @vamsiautomatad @w1kke @seruman @Chaz6 @PaoloCifariello @sd2k @mbana @exgens @aleksandersumowski @cbonitz @RMKD @ocramz @BrunoScheufler @igponce @ZhangHanDong @sergey-melnychuk @nottxy @Ruslanmsv @grovesNL @gklein @seeekr @lifa123 @ratamovic @andriisoldatenko @placrosse @sjaek @rjammala @serega @dgolhiardi @rogersmarin @damianmoore @dojiong @haraball @simple555a @piggybox @alexsward @mxuribe @syegulalp

point_up Ballista has moved to https://github.com/apache/arrow-datafusion .. could you do me a favor and star the new repo?

**Comment by andygrove** [comment]
@Julianobsg @songzhi @assertnotnull @QipengZhou @remingtonc @theikkila @alexkyllo @bdittmer @rootbid @porkcharsui @tkersey @davidli2010 @robbinhan @sdeancos @wolfymaster @jenhsun @clehene @apaz037 @max-sixty @dougb @rch @diop @tkshnwesper @iammohan83 @jonbaer @lovesegfault @joar @classmember @ziggyzacks @brunt @tzumby @wshobson @jwdeitch @winding-lines @bhattisatish @rolandjohann @rrichardson @atomic77 @flodiebold @orhanbalci @grapemix @shirshak55 @r0xsh @DenysNunes @vsayer @sguzman @ulopong @gblpedia @Xudong-Huang @mlinksva

:point_up: Ballista has moved to https://github.com/apache/arrow-datafusion .. could you do me a favor and star the new repo?

**Comment by lovesegfault** [comment]
You must be out of your mind if you think it's okay to spam everyone so they can star your repo. Please stop.

**Comment by andygrove** [comment]
I apologize. We lost the stars when moving the repo and I know a lot of people were wanting to follow this, but I will find a more appropriate way to get the news out.
