### ISSUE TITLE
Add support for HDFS

### ISSUE THREAD

**Issue by dthg** [ballista-compute/ballista#67]
As discussed on Gitter it would be great Ballista could read and write from HDFS.

Ideally Ballista would have a common way of accessing data from various sources such as S3 or other object stores.

What would the timeline for support here look like? I guess the initial steps would be to design the storage API, which arbitrary sources could access?

In terms of Rust support for HDFS, I haven't seen any particularly mature implementations. Do you see this (or a child project) as the place for that work to go? Or would that be more in the realm of Arrow?

Sorry if I've missed anything here or looked over something obvious, still in the grokking phase of Ballista but like what it does for distributed compute with rust. HDFS Support would really unblock things for me wrt to using rust in a professional capacity.

**Comment by andygrove** [comment]
Ballista now supports both Rust and Java executors, so maybe we can leverage Hadoop Java libraries for reading from HDFS and have Rust executors pull that data. Rust and Java executors can be co-located in the same pod.
